# 01 - Synthetic Data Generation

Цель: визуально проверить synthetic dataset COMPASS AI.

In [1]:
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path.cwd()
if not (ROOT / "data").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT))

DATA_SYNTHETIC = ROOT / "data" / "synthetic"
DATA_PROCESSED = ROOT / "data" / "processed"
REPORTS = ROOT / "reports"
FIGURES = REPORTS / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)

pd.set_option("display.max_columns", 80)
pd.set_option("display.width", 160)

print("Project root:", ROOT)

Project root: /Users/andrey/Documents/projects/COMPASS-AI

In [2]:
import yaml

config_path = ROOT / "config" / "synthetic_data.yaml"
schema_path = ROOT / "config" / "synthetic_schema.yaml"

with open(config_path, encoding="utf-8") as file:
    synthetic_config = yaml.safe_load(file)

with open(schema_path, encoding="utf-8") as file:
    synthetic_schema = yaml.safe_load(file)

display(synthetic_config)
display(synthetic_schema)

{'random_seed': 42,
 'employees_count': 36,
 'tasks_count': 2500,
 'assignments_count': 60000,
 'date_range_start': '2023-01-01',
 'date_range_end': '2026-06-30',
 'output': {'employees_csv': 'data/synthetic/employees.csv',
  'employees_json': 'data/synthetic/employees.json',
  'tasks_csv': 'data/synthetic/tasks.csv',
  'tasks_json': 'data/synthetic/tasks.json',
  'assignments_csv': 'data/synthetic/assignments.csv',
  'assignments_json': 'data/synthetic/assignments.json'},
 'projects': {'BACK': {'name': 'Backend Platform',
   'plane_project_id': 'e608e7ad-f4fe-401d-b0f3-5570e82f08ee',
   'weight': 0.45},
  'FRONT': {'name': 'Frontend Platform',
   'plane_project_id': '33832fc6-ade4-4ac0-a937-9ba70b0859d8',
   'weight': 0.25},
  'DATA': {'name': 'Data Platform',
   'plane_project_id': 'cdbeb78a-e8d3-4277-ad9b-13d6b8e44dab',
   'weight': 0.2},
  'TOOLS': {'name': 'Internal Tools',
   'plane_project_id': '50d969c6-ae4c-4afe-a8aa-33cdb478f787',
   'weight': 0.1}},
 'employee_generation': {'timezone': 'Europe/Berlin',
  'role_grade_plan': {'backend_developer': {'junior': 4,
    'middle': 6,
    'senior': 4},
   'frontend_developer': {'junior': 3, 'middle': 4, 'senior': 2},
   'qa_engineer': {'junior': 1, 'middle': 2, 'senior': 1},
   'data_ml_engineer': {'junior': 1, 'middle': 2, 'senior': 1},
   'devops_engineer': {'middle': 1, 'senior': 2},
   'team_lead': {'lead': 2}},
  'synthetic_names': ['Анна Смирнова',
   'Иван Петров',
   'Мария Кузнецова',
   'Дмитрий Соколов',
   'Екатерина Новикова',
   'Максим Орлов',
   'Ольга Волкова',
   'Алексей Морозов',
   'Наталья Фёдорова',
   'Сергей Павлов',
   'Полина Васильева',
   'Артём Михайлов',
   'Ксения Лебедева',
   'Никита Егоров',
   'Виктория Захарова',
   'Роман Киселёв',
   'Алиса Белова',
   'Андрей Громов',
   'Елена Романова',
   'Михаил Андреев',
   'Юлия Захарова',
   'Павел Волков',
   'Дарья Соловьёва',
   'Илья Комаров',
   'Анастасия Беляева',
   'Кирилл Никитин',
   'Валерия Фомина',
   'Денис Макаров',
   'Софья Гусева',
   'Тимофей Ковалёв',
   'Вероника Миронова',
   'Григорий Ларионов',
   'Милана Сафонова',
   'Владислав Титов',
   'Арина Королёва',
   'Матвей Фролов'],
  'workload_distribution': {'low': 0.18,
   'normal': 0.42,
   'high': 0.25,
   'risky': 0.11,
   'critical': 0.04}},
 'task_generation': {'priorities': {'none': 0.04,
   'low': 0.14,
   'medium': 0.42,
   'high': 0.28,
   'urgent': 0.12},
  'growth_task_probability': 0.22,
  'complexity_noise': 1,
  'deadline_days': {'min': 1, 'max': 60},
  'estimated_hours': {'min': 1, 'max': 120},
  'dependencies_count': {'min': 0, 'max': 8}},
 'assignment_generation': {'candidate_pool_size': 8,
  'min_actual_hours_multiplier': 0.45,
  'max_actual_hours_multiplier': 2.4,
  'reopened_count_max': 7,
  'manager_rating_min': 1,
  'manager_rating_max': 5,
  'success_probability_noise': 0.12,
  'scenario_weights': {'ideal_match': 0.28,
   'balanced_match': 0.24,
   'growth_stretch': 0.15,
   'overload_risk': 0.09,
   'wrong_role': 0.08,
   'urgent_deadline': 0.09,
   'random_assignment': 0.07},
  'outcome_distribution': {'full_success': 0.48,
   'partial_success': 0.16,
   'delayed_delivery': 0.16,
   'failed_delivery': 0.14,
   'cancelled_or_not_finished': 0.06}}}

{'version': 1,
 'team': {'employees_count': 36,
  'timezone': 'Europe/Berlin',
  'roles': {'backend_developer': {'display_name': 'Backend Developer',
    'target_count': 14,
    'allowed_grades': ['junior', 'middle', 'senior'],
    'primary_stack': 'backend_python'},
   'frontend_developer': {'display_name': 'Frontend Developer',
    'target_count': 9,
    'allowed_grades': ['junior', 'middle', 'senior'],
    'primary_stack': 'frontend_react'},
   'qa_engineer': {'display_name': 'QA Engineer',
    'target_count': 4,
    'allowed_grades': ['junior', 'middle', 'senior'],
    'primary_stack': 'qa_automation'},
   'data_ml_engineer': {'display_name': 'Data/ML Engineer',
    'target_count': 4,
    'allowed_grades': ['junior', 'middle', 'senior'],
    'primary_stack': 'data_ml'},
   'devops_engineer': {'display_name': 'DevOps Engineer',
    'target_count': 3,
    'allowed_grades': ['middle', 'senior'],
    'primary_stack': 'devops_platform'},
   'team_lead': {'display_name': 'Team Lead',
    'target_count': 2,
    'allowed_grades': ['lead'],
    'primary_stack': 'team_management'}},
  'employee_fields': ['employee_id',
   'plane_user_id',
   'name',
   'role',
   'grade',
   'experience_years',
   'primary_stack',
   'skills',
   'current_workload',
   'active_tasks_count',
   'avg_completion_speed',
   'avg_quality_score',
   'deadline_reliability',
   'learning_goals',
   'mentor_level',
   'availability',
   'timezone'],
  'workload_ranges': {'low': {'min': 0.0, 'max': 0.4},
   'normal': {'min': 0.4, 'max': 0.7},
   'high': {'min': 0.7, 'max': 0.85},
   'risky': {'min': 0.85, 'max': 0.95},
   'critical': {'min': 0.95, 'max': 1.0}},
  'experience_years_ranges': {'junior': {'min': 0.5, 'max': 2.0},
   'middle': {'min': 2.0, 'max': 5.0},
   'senior': {'min': 5.0, 'max': 9.0},
   'lead': {'min': 7.0, 'max': 12.0}},
  'availability_values': ['available', 'partially_available', 'unavailable']},
 'skills': {'level_scale': {0: 'no_skill',
   1: 'basic_awareness',
   2: 'simple_tasks',
   3: 'working_level',
   4: 'strong_level',
   5: 'expert_level'},
  'technical': ['Python',
   'FastAPI',
   'Django',
   'PostgreSQL',
   'Redis',
   'Docker',
   'Kubernetes',
   'React',
   'TypeScript',
   'Next.js',
   'HTML/CSS',
   'Testing',
   'CI/CD',
   'Data Analysis',
   'Machine Learning',
   'PyTorch',
   'API Design',
   'System Design',
   'Monitoring',
   'Security'],
  'soft_management': ['communication',
   'ownership',
   'mentoring',
   'documentation',
   'code_review',
   'planning',
   'risk_management'],
  'domain': ['backend_architecture',
   'frontend_architecture',
   'qa_strategy',
   'data_pipelines',
   'ml_experimentation',
   'devops_operations',
   'product_thinking',
   'team_coordination'],
  'role_skill_profiles': {'backend_developer': {'primary': ['Python',
     'FastAPI',
     'PostgreSQL',
     'Redis',
     'Docker',
     'API Design',
     'Testing',
     'System Design'],
    'secondary': ['CI/CD',
     'Monitoring',
     'Security',
     'documentation',
     'code_review']},
   'frontend_developer': {'primary': ['React',
     'TypeScript',
     'Next.js',
     'HTML/CSS',
     'Testing',
     'API Design'],
    'secondary': ['documentation',
     'code_review',
     'communication',
     'frontend_architecture']},
   'qa_engineer': {'primary': ['Testing',
     'API Design',
     'documentation',
     'risk_management'],
    'secondary': ['Python', 'CI/CD', 'Monitoring', 'qa_strategy']},
   'data_ml_engineer': {'primary': ['Python',
     'Data Analysis',
     'Machine Learning',
     'PyTorch',
     'data_pipelines',
     'ml_experimentation'],
    'secondary': ['PostgreSQL', 'Docker', 'Testing', 'documentation']},
   'devops_engineer': {'primary': ['Docker',
     'Kubernetes',
     'CI/CD',
     'Monitoring',
     'Security',
     'devops_operations'],
    'secondary': ['Python', 'PostgreSQL', 'Redis', 'risk_management']},
   'team_lead': {'primary': ['planning',
     'risk_management',
     'mentoring',
     'communication',
     'ownership',
     'team_coordination',
     'System Design',
     'code_review'],
    'secondary': ['API Design',
     'documentation',
     'backend_architecture',
     'product_thinking']}}},
 'tasks': {'task_types': {'backend_feature': {'average_complexity': 3,
    'default_required_skills': {'Python': 3,
     'FastAPI': 3,
     'PostgreSQL': 2,
     'API Design': 3,
     'Testing': 2},
    'default_project_key': 'BACK'},
   'frontend_feature': {'average_complexity': 3,
    'default_required_skills': {'React': 3,
     'TypeScript': 3,
     'Next.js': 2,
     'HTML/CSS': 3,
     'Testing': 2},
    'default_project_key': 'FRONT'},
   'bugfix': {'average_complexity': 2,
    'default_required_skills': {'Testing': 3,
     'Monitoring': 2,
     'API Design': 2},
    'default_project_key': 'BACK'},
   'refactoring': {'average_complexity': 3,
    'default_required_skills': {'System Design': 3,
     'Testing': 3,
     'code_review': 3,
     'documentation': 2},
    'default_project_key': 'BACK'},
   'database_migration': {'average_complexity': 4,
    'default_required_skills': {'PostgreSQL': 4,
     'System Design': 3,
     'Testing': 3,
     'risk_management': 3},
    'default_project_key': 'BACK'},
   'api_integration': {'average_complexity': 3,
    'default_required_skills': {'API Design': 3,
     'FastAPI': 3,
     'Testing': 2,
     'documentation': 2},
    'default_project_key': 'BACK'},
   'ml_pipeline': {'average_complexity': 4,
    'default_required_skills': {'Python': 4,
     'Machine Learning': 3,
     'PyTorch': 3,
     'Data Analysis': 3,
     'data_pipelines': 3},
    'default_project_key': 'DATA'},
   'analytics_report': {'average_complexity': 3,
    'default_required_skills': {'Data Analysis': 3,
     'PostgreSQL': 2,
     'Python': 2,
     'documentation': 2},
    'default_project_key': 'DATA'},
   'devops_task': {'average_complexity': 4,
    'default_required_skills': {'Docker': 4,
     'CI/CD': 3,
     'Monitoring': 3,
     'Security': 2},
    'default_project_key': 'TOOLS'},
   'testing_task': {'average_complexity': 2,
    'default_required_skills': {'Testing': 4,
     'documentation': 2,
     'API Design': 2},
    'default_project_key': 'BACK'},
   'security_task': {'average_complexity': 4,
    'default_required_skills': {'Security': 4,
     'System Design': 3,
     'risk_management': 3,
     'Testing': 3},
    'default_project_key': 'BACK'},
   'documentation_task': {'average_complexity': 1,
    'default_required_skills': {'documentation': 4,
     'communication': 2,
     'ownership': 2},
    'default_project_key': 'TOOLS'}},
  'task_fields': ['task_id',
   'plane_work_item_id',
   'plane_issue_id',
   'plane_project_id',
   'project_key',
   'title',
   'description',
   'task_type',
   'required_stack',
   'required_skills',
   'complexity',
   'priority',
   'business_criticality',
   'deadline_days',
   'estimated_hours',
   'dependencies_count',
   'is_growth_task',
   'source',
   'created_at',
   'updated_at'],
  'priorities': ['none', 'low', 'medium', 'high', 'urgent'],
  'project_keys': {'BACK': 'Backend Platform',
   'FRONT': 'Frontend Platform',
   'DATA': 'Data Platform',
   'TOOLS': 'Internal Tools'},
  'plane_mapping': {'id': 'plane_work_item_id',
   'name': 'title',
   'description_html': 'description',
   'priority': 'priority',
   'target_date': 'deadline_days',
   'project': 'plane_project_id',
   'labels': 'required_stack',
   'estimate_point': 'estimated_hours',
   'state': 'workflow_states'}},
 'assignments': {'assignment_fields': ['assignment_id',
   'task_id',
   'employee_id',
   'plane_work_item_id',
   'plane_issue_id',
   'assigned_at',
   'completed_at',
   'completed_on_time',
   'estimated_hours',
   'actual_hours',
   'quality_score',
   'reopened_count',
   'manager_rating',
   'employee_workload_at_assignment',
   'skill_match_score',
   'growth_match_score',
   'speed_score',
   'collaboration_score',
   'risk_score',
   'success_probability',
   'assignment_scenario',
   'outcome_status',
   'delay_days',
   'delivery_speed_category',
   'success_label'],
  'success_label': {'positive_rule': {'completed_on_time': True,
    'min_quality_score': 0.75,
    'max_reopened_count': 1,
    'max_employee_workload_at_assignment': 0.85},
   'negative_rule': {'completed_on_time': False,
    'max_quality_score': 0.6,
    'min_reopened_count': 3,
    'min_employee_workload_at_assignment': 0.95}},
  'success_probability_weights': {'skill_match_score': 0.35,
   'deadline_reliability': 0.2,
   'avg_quality_score': 0.15,
   'avg_completion_speed': 0.1,
   'collaboration_score': 0.1,
   'growth_match_score': 0.1,
   'overload_penalty': -0.25,
   'complexity_gap_penalty': -0.15},
  'overload_penalty': {'low_or_normal': {'max_workload': 0.7, 'penalty': 0.0},
   'high': {'min_workload': 0.7, 'max_workload': 0.85, 'penalty': 0.2},
   'risky': {'min_workload': 0.85, 'max_workload': 0.95, 'penalty': 0.5},
   'critical': {'min_workload': 0.95, 'max_workload': 1.0, 'penalty': 0.8}},
  'comfortable_complexity_by_grade': {'junior': {'min': 1, 'max': 2},
   'middle': {'min': 2, 'max': 4},
   'senior': {'min': 3, 'max': 5},
   'lead': {'min': 4, 'max': 5}},
  'label_values': [0, 1],
  'outcome_status_values': ['full_success',
   'partial_success',
   'delayed_delivery',
   'failed_delivery',
   'cancelled_or_not_finished'],
  'delivery_speed_categories': ['very_fast',
   'on_time',
   'slightly_delayed',
   'heavily_delayed',
   'not_finished'],
  'assignment_scenarios': ['ideal_match',
   'balanced_match',
   'growth_stretch',
   'overload_risk',
   'wrong_role',
   'urgent_deadline',
   'random_assignment']}}

In [3]:
employees = pd.read_csv(DATA_SYNTHETIC / "employees.csv")
tasks = pd.read_csv(DATA_SYNTHETIC / "tasks.csv")
assignments = pd.read_csv(DATA_SYNTHETIC / "assignments.csv")

print("employees:", employees.shape)
print("tasks:", tasks.shape)
print("assignments:", assignments.shape)

employees: (36, 17)
tasks: (2500, 20)
assignments: (60000, 25)

In [4]:
display(employees.head(10))

,employee_id,plane_user_id,name,role,grade,experience_years,primary_stack,skills,current_workload,active_tasks_count,avg_completion_speed,avg_quality_score,deadline_reliability,learning_goals,mentor_level,availability,timezone
0,EMP-001,NaN,Анна Смирнова,backend_developer,junior,0.7,backend_python,"{""API Design"": 2, ""CI/CD"": 2, ""Data Analysis"":...",0.629,4,0.639,0.703,0.615,"[""FastAPI"", ""Python"", ""Redis"", ""documentation""]",0,available,Europe/Berlin
1,EMP-002,NaN,Иван Петров,backend_developer,junior,1.1,backend_python,"{""API Design"": 1, ""CI/CD"": 1, ""Data Analysis"":...",0.597,7,0.669,0.621,0.612,"[""API Design"", ""PostgreSQL"", ""Redis""]",1,available,Europe/Berlin
2,EMP-003,NaN,Мария Кузнецова,backend_developer,junior,0.8,backend_python,"{""API Design"": 1, ""CI/CD"": 2, ""Data Analysis"":...",0.776,5,0.717,0.616,0.655,"[""FastAPI"", ""documentation""]",1,available,Europe/Berlin
3,EMP-004,NaN,Дмитрий Соколов,backend_developer,junior,0.8,backend_python,"{""API Design"": 2, ""CI/CD"": 1, ""Data Analysis"":...",0.252,3,0.531,0.659,0.912,"[""System Design"", ""code_review""]",0,available,Europe/Berlin
4,EMP-005,NaN,Екатерина Новикова,backend_developer,middle,4.8,backend_python,"{""API Design"": 2, ""CI/CD"": 1, ""Data Analysis"":...",0.845,9,0.598,0.716,0.666,"[""CI/CD"", ""Monitoring"", ""Testing""]",3,available,Europe/Berlin
5,EMP-006,NaN,Максим Орлов,backend_developer,middle,4.8,backend_python,"{""API Design"": 3, ""CI/CD"": 1, ""Data Analysis"":...",0.557,3,0.774,0.741,0.745,"[""CI/CD"", ""Security""]",1,available,Europe/Berlin
6,EMP-007,NaN,Ольга Волкова,backend_developer,middle,4.5,backend_python,"{""API Design"": 2, ""CI/CD"": 3, ""Data Analysis"":...",0.672,3,0.700,0.819,0.902,"[""FastAPI"", ""PostgreSQL"", ""Python"", ""documenta...",3,available,Europe/Berlin
7,EMP-008,NaN,Алексей Морозов,backend_developer,middle,4.4,backend_python,"{""API Design"": 4, ""CI/CD"": 2, ""Data Analysis"":...",0.872,7,0.540,0.719,0.684,"[""FastAPI"", ""Python"", ""System Design"", ""Testing""]",3,partially_available,Europe/Berlin
8,EMP-009,NaN,Наталья Фёдорова,backend_developer,middle,2.6,backend_python,"{""API Design"": 2, ""CI/CD"": 3, ""Data Analysis"":...",0.783,7,0.629,0.673,0.693,"[""CI/CD"", ""Docker"", ""Testing""]",2,available,Europe/Berlin
9,EMP-010,NaN,Сергей Павлов,backend_developer,middle,4.7,backend_python,"{""API Design"": 3, ""CI/CD"": 1, ""Data Analysis"":...",0.275,3,0.449,0.846,0.931,"[""API Design"", ""CI/CD"", ""Security""]",1,available,Europe/Berlin

In [5]:
display(tasks.head(10))

,task_id,plane_work_item_id,plane_issue_id,plane_project_id,project_key,title,description,task_type,required_stack,required_skills,complexity,priority,business_criticality,deadline_days,estimated_hours,dependencies_count,is_growth_task,source,created_at,updated_at
0,TASK-0001,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Добавить endpoint для статистики команды — инт...,"Реализовать backend endpoint, который возвраща...",backend_feature,"[""Python"", ""FastAPI"", ""PostgreSQL""]","{""API Design"": 3, ""FastAPI"": 3, ""PostgreSQL"": ...",4,medium,3,30,33,8,False,synthetic,2025-06-04T00:00:00,2025-06-22T00:00:00
1,TASK-0002,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Добавить healthcheck для COMPASS API — интегра...,Настроить endpoint и проверку доступности back...,devops_task,"[""Docker""]","{""CI/CD"": 3, ""Docker"": 4, ""Monitoring"": 3, ""Se...",3,low,2,11,40,6,False,synthetic,2026-05-08T00:00:00,2026-05-24T00:00:00
2,TASK-0003,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Исправить падение API при пустом описании зада...,Добавить корректную обработку задач без descri...,bugfix,[],"{""API Design"": 2, ""Monitoring"": 2, ""Testing"": 3}",1,medium,1,19,16,1,False,synthetic,2026-04-11T00:00:00,2026-05-01T00:00:00
3,TASK-0004,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Проверить отсутствие секретов в логах — экспор...,"Убедиться, что API tokens и .env значения не п...",security_task,[],"{""Security"": 4, ""System Design"": 3, ""Testing"":...",5,high,5,22,41,2,False,synthetic,2023-09-16T00:00:00,2023-09-18T00:00:00
4,TASK-0005,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Добавить фильтрацию задач по статусу — модуля ...,"Расширить API задач фильтрами по статусу, прио...",backend_feature,"[""Python"", ""FastAPI"", ""PostgreSQL""]","{""API Design"": 3, ""FastAPI"": 3, ""PostgreSQL"": ...",2,high,4,43,19,5,False,synthetic,2025-06-07T00:00:00,2025-06-08T00:00:00
5,TASK-0006,NaN,NaN,cdbeb78a-e8d3-4277-ad9b-13d6b8e44dab,DATA,Реализовать baseline для сравнения с нейросеть...,"Собрать rule-based ranking, чтобы сравнивать M...",ml_pipeline,"[""Python"", ""PyTorch""]","{""Data Analysis"": 3, ""Machine Learning"": 3, ""P...",5,high,5,10,41,8,False,synthetic,2025-05-19T00:00:00,2025-06-02T00:00:00
6,TASK-0007,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Починить ошибку при смене assignee — аналитиче...,"Исправить сценарий, при котором задача может п...",bugfix,[],"{""API Design"": 2, ""Monitoring"": 2, ""Testing"": 3}",2,none,1,46,20,7,True,synthetic,2024-11-27T00:00:00,2024-12-09T00:00:00
7,TASK-0008,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Реализовать JWT-авторизацию — пайплайна рекоме...,"Добавить login endpoint, refresh token flow, l...",backend_feature,"[""Python"", ""FastAPI"", ""PostgreSQL""]","{""API Design"": 3, ""FastAPI"": 3, ""PostgreSQL"": ...",2,high,4,60,31,6,False,synthetic,2024-11-01T00:00:00,2024-11-13T00:00:00
8,TASK-0009,NaN,NaN,e608e7ad-f4fe-401d-b0f3-5570e82f08ee,BACK,Починить некорректный расчёт дедлайна — пайпла...,Исправить расчёт deadline_days для задач без t...,bugfix,[],"{""API Design"": 2, ""Monitoring"": 2, ""Testing"": 3}",3,urgent,3,20,15,3,False,synthetic,2025-02-24T00:00:00,2025-03-08T00:00:00
9,TASK-0010,NaN,NaN,33832fc6-ade4-4ac0-a937-9ba70b0859d8,FRONT,Добавить график распределения workload — анали...,Построить график текущей загрузки команды и вы...,analytics_report,"[""PostgreSQL"", ""Python""]","{""Data Analysis"": 3, ""PostgreSQL"": 2, ""Python""...",4,high,5,56,30,5,True,synthetic,2024-06-23T00:00:00,2024-06-30T00:00:00

In [6]:
display(assignments.head(10))

,assignment_id,task_id,employee_id,plane_work_item_id,plane_issue_id,assigned_at,completed_at,completed_on_time,estimated_hours,actual_hours,quality_score,reopened_count,manager_rating,employee_workload_at_assignment,skill_match_score,growth_match_score,speed_score,collaboration_score,risk_score,success_probability,assignment_scenario,outcome_status,delay_days,delivery_speed_category,success_label
0,ASN-000001,TASK-2437,EMP-024,NaN,NaN,2023-05-31T00:00:00,2023-06-25T00:00:00,True,16.0,11.6,0.9079,1,5,0.3311,0.5000,0.3333,0.6968,0.520,0.1840,0.6057,balanced_match,full_success,0,very_fast,1
1,ASN-000002,TASK-2278,EMP-029,NaN,NaN,2024-11-04T00:00:00,2024-11-07T00:00:00,True,43.0,44.0,0.7565,1,4,0.9434,0.4375,0.5000,0.6363,0.585,0.3498,0.3944,balanced_match,partial_success,0,on_time,0
2,ASN-000003,TASK-0023,EMP-024,NaN,NaN,2026-01-17T00:00:00,2026-02-27T00:00:00,True,25.0,30.6,0.9089,0,5,0.3832,0.5000,0.3333,0.6968,0.520,0.1200,0.6952,balanced_match,full_success,0,on_time,1
3,ASN-000004,TASK-1227,EMP-025,NaN,NaN,2025-12-08T00:00:00,2026-01-31T00:00:00,True,43.0,33.6,0.9144,0,4,0.7375,0.6458,0.2500,0.6906,0.650,0.2758,0.6104,balanced_match,full_success,0,on_time,1
4,ASN-000005,TASK-1382,EMP-023,NaN,NaN,2024-10-12T00:00:00,2024-12-26T00:00:00,False,50.0,137.4,0.3812,5,2,0.6165,0.5625,0.2500,0.9235,0.815,0.4036,0.2825,growth_stretch,failed_delivery,22,heavily_delayed,0
5,ASN-000006,TASK-2124,EMP-036,NaN,NaN,2025-10-29T00:00:00,2025-11-30T00:00:00,True,12.0,16.5,0.8312,0,4,0.8727,0.9167,0.3333,0.7395,0.945,0.3440,0.8450,ideal_match,full_success,0,on_time,1
6,ASN-000007,TASK-0851,EMP-022,NaN,NaN,2023-11-17T00:00:00,2023-12-27T00:00:00,True,18.0,29.8,0.8534,1,5,0.6382,1.0000,0.0000,0.7478,0.815,0.2260,0.8757,ideal_match,full_success,0,on_time,1
7,ASN-000008,TASK-0724,EMP-008,NaN,NaN,2023-11-28T00:00:00,2024-01-18T00:00:00,False,31.0,31.2,0.6407,2,3,0.7316,1.0000,0.5000,0.4482,0.715,0.3208,0.3457,overload_risk,delayed_delivery,4,slightly_delayed,0
8,ASN-000009,TASK-0156,EMP-017,NaN,NaN,2024-07-16T00:00:00,2024-08-30T00:00:00,False,46.0,46.7,0.2335,3,3,1.0000,0.4792,0.0000,0.4212,0.585,0.7716,0.0200,overload_risk,failed_delivery,27,slightly_delayed,0
9,ASN-000010,TASK-2353,EMP-008,NaN,NaN,2025-02-12T00:00:00,2025-04-16T00:00:00,False,18.0,34.9,0.7785,2,3,0.8888,1.0000,0.5000,0.4482,0.715,0.3208,0.4802,random_assignment,delayed_delivery,13,heavily_delayed,0

In [7]:
import plotly.express as px

role_counts = employees["role"].value_counts().reset_index()
role_counts.columns = ["role", "count"]

fig = px.bar(role_counts, x="role", y="count")
fig.update_layout(title="Employees by role")
fig.show()

In [8]:
import plotly.express as px

fig = px.histogram(
    tasks,
    x="complexity",
    color="project_key",
    barmode="group",
)
fig.update_layout(title="Task complexity by project")
fig.show()

In [9]:
import plotly.express as px

success_counts = (
    assignments["success_label"]
    .value_counts()
    .sort_index()
    .reset_index()
)
success_counts.columns = ["success_label", "count"]

fig = px.bar(success_counts, x="success_label", y="count")
fig.update_layout(title="Success label distribution")
fig.show()

In [10]:
import plotly.express as px

outcome_counts = assignments["outcome_status"].value_counts().reset_index()
outcome_counts.columns = ["outcome_status", "count"]

fig = px.bar(outcome_counts, x="outcome_status", y="count")
fig.update_layout(title="Assignment outcomes")
fig.show()